#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_XEMAY")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHITIETHD(CHITIETHD instance);
    partial void UpdateCHITIETHD(CHITIETHD instance);
    partial void DeleteCHITIETHD(CHITIETHD instance);
    partial void InsertXEMAY(XEMAY instance);
    partial void UpdateXEMAY(XEMAY instance);
    partial void DeleteXEMAY(XEMAY instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLOAIXE(LOAIXE instance);
    partial void UpdateLOAIXE(LOAIXE instance);
    partial void DeleteLOAIXE(LOAIXE instance);
    partial void InsertNCC_XEMAY(NCC_XEMAY instance);
    partial void UpdateNCC_XEMAY(NCC_XEMAY instance);
    partial void DeleteNCC_XEMAY(NCC_XEMAY instance);
    partial void InsertNHACUNGCAP(NHACUNGCAP instance);
    partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
    partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
    partial void InsertTHUONGHIEUXE(THUONGHIEUXE instance);
    partial void UpdateTHUONGHIEUXE(THUONGHIEUXE instance);
    partial void DeleteTHUONGHIEUXE(THUONGHIEUXE instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

        public DataClasses1DataContext():
            base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_XEMAYConnectionString"].ConnectionString, mappingSource)
        {
			OnCreated();
        }

        public System.Data.Linq.Table<CHITIETHD> CHITIETHDs
		{
			get
			{
				return this.GetTable<CHITIETHD>();
			}
		}
		
		public System.Data.Linq.Table<XEMAY> XEMAYs
		{
			get
			{
				return this.GetTable<XEMAY>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAIXE> LOAIXEs
		{
			get
			{
				return this.GetTable<LOAIXE>();
			}
		}
		
		public System.Data.Linq.Table<NCC_XEMAY> NCC_XEMAYs
		{
			get
			{
				return this.GetTable<NCC_XEMAY>();
			}
		}
		
		public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this.GetTable<NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<THUONGHIEUXE> THUONGHIEUXEs
		{
			get
			{
				return this.GetTable<THUONGHIEUXE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHD")]
	public partial class CHITIETHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHOADON;
		
		private string _MACC_XEMAY;
		
		private System.Nullable<int> _SOLUONGMUA;
		
		private System.Nullable<decimal> _DONGIA;
		
		private EntityRef<HOADON> _HOADON;
		
		private EntityRef<NCC_XEMAY> _NCC_XEMAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHOADONChanging(string value);
    partial void OnMAHOADONChanged();
    partial void OnMACC_XEMAYChanging(string value);
    partial void OnMACC_XEMAYChanged();
    partial void OnSOLUONGMUAChanging(System.Nullable<int> value);
    partial void OnSOLUONGMUAChanged();
    partial void OnDONGIAChanging(System.Nullable<decimal> value);
    partial void OnDONGIAChanged();
    #endregion
		
		public CHITIETHD()
		{
			this._HOADON = default(EntityRef<HOADON>);
			this._NCC_XEMAY = default(EntityRef<NCC_XEMAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHOADON", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHOADON
		{
			get
			{
				return this._MAHOADON;
			}
			set
			{
				if ((this._MAHOADON != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHOADONChanging(value);
					this.SendPropertyChanging();
					this._MAHOADON = value;
					this.SendPropertyChanged("MAHOADON");
					this.OnMAHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACC_XEMAY", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACC_XEMAY
		{
			get
			{
				return this._MACC_XEMAY;
			}
			set
			{
				if ((this._MACC_XEMAY != value))
				{
					if (this._NCC_XEMAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACC_XEMAYChanging(value);
					this.SendPropertyChanging();
					this._MACC_XEMAY = value;
					this.SendPropertyChanged("MACC_XEMAY");
					this.OnMACC_XEMAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGMUA", DbType="Int")]
		public System.Nullable<int> SOLUONGMUA
		{
			get
			{
				return this._SOLUONGMUA;
			}
			set
			{
				if ((this._SOLUONGMUA != value))
				{
					this.OnSOLUONGMUAChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGMUA = value;
					this.SendPropertyChanged("SOLUONGMUA");
					this.OnSOLUONGMUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Money")]
		public System.Nullable<decimal> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CHITIETHD", Storage="_HOADON", ThisKey="MAHOADON", OtherKey="MAHOADON", IsForeignKey=true)]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CHITIETHDs.Remove(this);
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CHITIETHDs.Add(this);
						this._MAHOADON = value.MAHOADON;
					}
					else
					{
						this._MAHOADON = default(string);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NCC_XEMAY_CHITIETHD", Storage="_NCC_XEMAY", ThisKey="MACC_XEMAY", OtherKey="MACC_XEMAY", IsForeignKey=true)]
		public NCC_XEMAY NCC_XEMAY
		{
			get
			{
				return this._NCC_XEMAY.Entity;
			}
			set
			{
				NCC_XEMAY previousValue = this._NCC_XEMAY.Entity;
				if (((previousValue != value) 
							|| (this._NCC_XEMAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NCC_XEMAY.Entity = null;
						previousValue.CHITIETHDs.Remove(this);
					}
					this._NCC_XEMAY.Entity = value;
					if ((value != null))
					{
						value.CHITIETHDs.Add(this);
						this._MACC_XEMAY = value.MACC_XEMAY;
					}
					else
					{
						this._MACC_XEMAY = default(string);
					}
					this.SendPropertyChanged("NCC_XEMAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.XEMAY")]
	public partial class XEMAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAXEMAY;
		
		private string _TENXEMAY;
		
		private System.Nullable<System.DateTime> _NGAYSANXUAT;
		
		private string _THOIGIANBAOHANH;
		
		private System.Nullable<decimal> _GIABANXE;
		
		private string _MALOAIXE;
		
		private string _MATHUONGHIEU;
		
		private string _HINHANH;
		
		private EntitySet<NCC_XEMAY> _NCC_XEMAYs;
		
		private EntityRef<LOAIXE> _LOAIXE;
		
		private EntityRef<THUONGHIEUXE> _THUONGHIEUXE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAXEMAYChanging(string value);
    partial void OnMAXEMAYChanged();
    partial void OnTENXEMAYChanging(string value);
    partial void OnTENXEMAYChanged();
    partial void OnNGAYSANXUATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSANXUATChanged();
    partial void OnTHOIGIANBAOHANHChanging(string value);
    partial void OnTHOIGIANBAOHANHChanged();
    partial void OnGIABANXEChanging(System.Nullable<decimal> value);
    partial void OnGIABANXEChanged();
    partial void OnMALOAIXEChanging(string value);
    partial void OnMALOAIXEChanged();
    partial void OnMATHUONGHIEUChanging(string value);
    partial void OnMATHUONGHIEUChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    #endregion
		
		public XEMAY()
		{
			this._NCC_XEMAYs = new EntitySet<NCC_XEMAY>(new Action<NCC_XEMAY>(this.attach_NCC_XEMAYs), new Action<NCC_XEMAY>(this.detach_NCC_XEMAYs));
			this._LOAIXE = default(EntityRef<LOAIXE>);
			this._THUONGHIEUXE = default(EntityRef<THUONGHIEUXE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXEMAY", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAXEMAY
		{
			get
			{
				return this._MAXEMAY;
			}
			set
			{
				if ((this._MAXEMAY != value))
				{
					this.OnMAXEMAYChanging(value);
					this.SendPropertyChanging();
					this._MAXEMAY = value;
					this.SendPropertyChanged("MAXEMAY");
					this.OnMAXEMAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENXEMAY", DbType="NVarChar(50)")]
		public string TENXEMAY
		{
			get
			{
				return this._TENXEMAY;
			}
			set
			{
				if ((this._TENXEMAY != value))
				{
					this.OnTENXEMAYChanging(value);
					this.SendPropertyChanging();
					this._TENXEMAY = value;
					this.SendPropertyChanged("TENXEMAY");
					this.OnTENXEMAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSANXUAT", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSANXUAT
		{
			get
			{
				return this._NGAYSANXUAT;
			}
			set
			{
				if ((this._NGAYSANXUAT != value))
				{
					this.OnNGAYSANXUATChanging(value);
					this.SendPropertyChanging();
					this._NGAYSANXUAT = value;
					this.SendPropertyChanged("NGAYSANXUAT");
					this.OnNGAYSANXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANBAOHANH", DbType="NVarChar(20)")]
		public string THOIGIANBAOHANH
		{
			get
			{
				return this._THOIGIANBAOHANH;
			}
			set
			{
				if ((this._THOIGIANBAOHANH != value))
				{
					this.OnTHOIGIANBAOHANHChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANBAOHANH = value;
					this.SendPropertyChanged("THOIGIANBAOHANH");
					this.OnTHOIGIANBAOHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABANXE", DbType="Money")]
		public System.Nullable<decimal> GIABANXE
		{
			get
			{
				return this._GIABANXE;
			}
			set
			{
				if ((this._GIABANXE != value))
				{
					this.OnGIABANXEChanging(value);
					this.SendPropertyChanging();
					this._GIABANXE = value;
					this.SendPropertyChanged("GIABANXE");
					this.OnGIABANXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIXE", DbType="NChar(10)")]
		public string MALOAIXE
		{
			get
			{
				return this._MALOAIXE;
			}
			set
			{
				if ((this._MALOAIXE != value))
				{
					if (this._LOAIXE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIXEChanging(value);
					this.SendPropertyChanging();
					this._MALOAIXE = value;
					this.SendPropertyChanged("MALOAIXE");
					this.OnMALOAIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUONGHIEU", DbType="NChar(10)")]
		public string MATHUONGHIEU
		{
			get
			{
				return this._MATHUONGHIEU;
			}
			set
			{
				if ((this._MATHUONGHIEU != value))
				{
					if (this._THUONGHIEUXE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHUONGHIEUChanging(value);
					this.SendPropertyChanging();
					this._MATHUONGHIEU = value;
					this.SendPropertyChanged("MATHUONGHIEU");
					this.OnMATHUONGHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(120)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XEMAY_NCC_XEMAY", Storage="_NCC_XEMAYs", ThisKey="MAXEMAY", OtherKey="MAXE")]
		public EntitySet<NCC_XEMAY> NCC_XEMAYs
		{
			get
			{
				return this._NCC_XEMAYs;
			}
			set
			{
				this._NCC_XEMAYs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIXE_XEMAY", Storage="_LOAIXE", ThisKey="MALOAIXE", OtherKey="MALOAIXE", IsForeignKey=true)]
		public LOAIXE LOAIXE
		{
			get
			{
				return this._LOAIXE.Entity;
			}
			set
			{
				LOAIXE previousValue = this._LOAIXE.Entity;
				if (((previousValue != value) 
							|| (this._LOAIXE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIXE.Entity = null;
						previousValue.XEMAYs.Remove(this);
					}
					this._LOAIXE.Entity = value;
					if ((value != null))
					{
						value.XEMAYs.Add(this);
						this._MALOAIXE = value.MALOAIXE;
					}
					else
					{
						this._MALOAIXE = default(string);
					}
					this.SendPropertyChanged("LOAIXE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONGHIEUXE_XEMAY", Storage="_THUONGHIEUXE", ThisKey="MATHUONGHIEU", OtherKey="MATHUONGHIEU", IsForeignKey=true)]
		public THUONGHIEUXE THUONGHIEUXE
		{
			get
			{
				return this._THUONGHIEUXE.Entity;
			}
			set
			{
				THUONGHIEUXE previousValue = this._THUONGHIEUXE.Entity;
				if (((previousValue != value) 
							|| (this._THUONGHIEUXE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUONGHIEUXE.Entity = null;
						previousValue.XEMAYs.Remove(this);
					}
					this._THUONGHIEUXE.Entity = value;
					if ((value != null))
					{
						value.XEMAYs.Add(this);
						this._MATHUONGHIEU = value.MATHUONGHIEU;
					}
					else
					{
						this._MATHUONGHIEU = default(string);
					}
					this.SendPropertyChanged("THUONGHIEUXE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NCC_XEMAYs(NCC_XEMAY entity)
		{
			this.SendPropertyChanging();
			entity.XEMAY = this;
		}
		
		private void detach_NCC_XEMAYs(NCC_XEMAY entity)
		{
			this.SendPropertyChanging();
			entity.XEMAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHOADON;
		
		private System.Nullable<System.DateTime> _NGAYDATHANG;
		
		private System.Nullable<System.DateTime> _NGAYGIAOHANG;
		
		private System.Nullable<decimal> _TONGTIEN;
		
		private System.Nullable<int> _TINHTRANGGIAOHANG;
		
		private string _MAKHACHHANG;
		
		private EntitySet<CHITIETHD> _CHITIETHDs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHOADONChanging(string value);
    partial void OnMAHOADONChanged();
    partial void OnNGAYDATHANGChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDATHANGChanged();
    partial void OnNGAYGIAOHANGChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYGIAOHANGChanged();
    partial void OnTONGTIENChanging(System.Nullable<decimal> value);
    partial void OnTONGTIENChanged();
    partial void OnTINHTRANGGIAOHANGChanging(System.Nullable<int> value);
    partial void OnTINHTRANGGIAOHANGChanged();
    partial void OnMAKHACHHANGChanging(string value);
    partial void OnMAKHACHHANGChanged();
    #endregion
		
		public HOADON()
		{
			this._CHITIETHDs = new EntitySet<CHITIETHD>(new Action<CHITIETHD>(this.attach_CHITIETHDs), new Action<CHITIETHD>(this.detach_CHITIETHDs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHOADON", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHOADON
		{
			get
			{
				return this._MAHOADON;
			}
			set
			{
				if ((this._MAHOADON != value))
				{
					this.OnMAHOADONChanging(value);
					this.SendPropertyChanging();
					this._MAHOADON = value;
					this.SendPropertyChanged("MAHOADON");
					this.OnMAHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDATHANG", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYDATHANG
		{
			get
			{
				return this._NGAYDATHANG;
			}
			set
			{
				if ((this._NGAYDATHANG != value))
				{
					this.OnNGAYDATHANGChanging(value);
					this.SendPropertyChanging();
					this._NGAYDATHANG = value;
					this.SendPropertyChanged("NGAYDATHANG");
					this.OnNGAYDATHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGIAOHANG", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYGIAOHANG
		{
			get
			{
				return this._NGAYGIAOHANG;
			}
			set
			{
				if ((this._NGAYGIAOHANG != value))
				{
					this.OnNGAYGIAOHANGChanging(value);
					this.SendPropertyChanging();
					this._NGAYGIAOHANG = value;
					this.SendPropertyChanged("NGAYGIAOHANG");
					this.OnNGAYGIAOHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Money")]
		public System.Nullable<decimal> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANGGIAOHANG", DbType="Int")]
		public System.Nullable<int> TINHTRANGGIAOHANG
		{
			get
			{
				return this._TINHTRANGGIAOHANG;
			}
			set
			{
				if ((this._TINHTRANGGIAOHANG != value))
				{
					this.OnTINHTRANGGIAOHANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANGGIAOHANG = value;
					this.SendPropertyChanged("TINHTRANGGIAOHANG");
					this.OnTINHTRANGGIAOHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHACHHANG", DbType="NChar(10)")]
		public string MAKHACHHANG
		{
			get
			{
				return this._MAKHACHHANG;
			}
			set
			{
				if ((this._MAKHACHHANG != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._MAKHACHHANG = value;
					this.SendPropertyChanged("MAKHACHHANG");
					this.OnMAKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CHITIETHD", Storage="_CHITIETHDs", ThisKey="MAHOADON", OtherKey="MAHOADON")]
		public EntitySet<CHITIETHD> CHITIETHDs
		{
			get
			{
				return this._CHITIETHDs;
			}
			set
			{
				this._CHITIETHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_KHACHHANG", ThisKey="MAKHACHHANG", OtherKey="MAKHACHHANG", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MAKHACHHANG = value.MAKHACHHANG;
					}
					else
					{
						this._MAKHACHHANG = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHDs(CHITIETHD entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = this;
		}
		
		private void detach_CHITIETHDs(CHITIETHD entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKHACHHANG;
		
		private string _TENKHACHHANG;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _SODIENTHOAI;
		
		private string _TAIKHOAN;
		
		private string _MATKHAU;
		
		private string _EMAIL;
		
		private string _DIACHI;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHACHHANGChanging(string value);
    partial void OnMAKHACHHANGChanged();
    partial void OnTENKHACHHANGChanging(string value);
    partial void OnTENKHACHHANGChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnSODIENTHOAIChanging(string value);
    partial void OnSODIENTHOAIChanged();
    partial void OnTAIKHOANChanging(string value);
    partial void OnTAIKHOANChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHACHHANG", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKHACHHANG
		{
			get
			{
				return this._MAKHACHHANG;
			}
			set
			{
				if ((this._MAKHACHHANG != value))
				{
					this.OnMAKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._MAKHACHHANG = value;
					this.SendPropertyChanged("MAKHACHHANG");
					this.OnMAKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHACHHANG", DbType="NVarChar(50)")]
		public string TENKHACHHANG
		{
			get
			{
				return this._TENKHACHHANG;
			}
			set
			{
				if ((this._TENKHACHHANG != value))
				{
					this.OnTENKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._TENKHACHHANG = value;
					this.SendPropertyChanged("TENKHACHHANG");
					this.OnTENKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODIENTHOAI", DbType="NChar(10)")]
		public string SODIENTHOAI
		{
			get
			{
				return this._SODIENTHOAI;
			}
			set
			{
				if ((this._SODIENTHOAI != value))
				{
					this.OnSODIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._SODIENTHOAI = value;
					this.SendPropertyChanged("SODIENTHOAI");
					this.OnSODIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIKHOAN", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN;
			}
			set
			{
				if ((this._TAIKHOAN != value))
				{
					this.OnTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN = value;
					this.SendPropertyChanged("TAIKHOAN");
					this.OnTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(30)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(30)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_HOADONs", ThisKey="MAKHACHHANG", OtherKey="MAKHACHHANG")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIXE")]
	public partial class LOAIXE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAIXE;
		
		private string _TENLOAIXE;
		
		private EntitySet<XEMAY> _XEMAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIXEChanging(string value);
    partial void OnMALOAIXEChanged();
    partial void OnTENLOAIXEChanging(string value);
    partial void OnTENLOAIXEChanged();
    #endregion
		
		public LOAIXE()
		{
			this._XEMAYs = new EntitySet<XEMAY>(new Action<XEMAY>(this.attach_XEMAYs), new Action<XEMAY>(this.detach_XEMAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIXE", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAIXE
		{
			get
			{
				return this._MALOAIXE;
			}
			set
			{
				if ((this._MALOAIXE != value))
				{
					this.OnMALOAIXEChanging(value);
					this.SendPropertyChanging();
					this._MALOAIXE = value;
					this.SendPropertyChanged("MALOAIXE");
					this.OnMALOAIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAIXE", DbType="NVarChar(30)")]
		public string TENLOAIXE
		{
			get
			{
				return this._TENLOAIXE;
			}
			set
			{
				if ((this._TENLOAIXE != value))
				{
					this.OnTENLOAIXEChanging(value);
					this.SendPropertyChanging();
					this._TENLOAIXE = value;
					this.SendPropertyChanged("TENLOAIXE");
					this.OnTENLOAIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIXE_XEMAY", Storage="_XEMAYs", ThisKey="MALOAIXE", OtherKey="MALOAIXE")]
		public EntitySet<XEMAY> XEMAYs
		{
			get
			{
				return this._XEMAYs;
			}
			set
			{
				this._XEMAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_XEMAYs(XEMAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIXE = this;
		}
		
		private void detach_XEMAYs(XEMAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIXE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NCC_XEMAY")]
	public partial class NCC_XEMAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACC_XEMAY;
		
		private string _MAXE;
		
		private string _MANCC;
		
		private EntitySet<CHITIETHD> _CHITIETHDs;
		
		private EntityRef<XEMAY> _XEMAY;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACC_XEMAYChanging(string value);
    partial void OnMACC_XEMAYChanged();
    partial void OnMAXEChanging(string value);
    partial void OnMAXEChanged();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    #endregion
		
		public NCC_XEMAY()
		{
			this._CHITIETHDs = new EntitySet<CHITIETHD>(new Action<CHITIETHD>(this.attach_CHITIETHDs), new Action<CHITIETHD>(this.detach_CHITIETHDs));
			this._XEMAY = default(EntityRef<XEMAY>);
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACC_XEMAY", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACC_XEMAY
		{
			get
			{
				return this._MACC_XEMAY;
			}
			set
			{
				if ((this._MACC_XEMAY != value))
				{
					this.OnMACC_XEMAYChanging(value);
					this.SendPropertyChanging();
					this._MACC_XEMAY = value;
					this.SendPropertyChanged("MACC_XEMAY");
					this.OnMACC_XEMAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXE", DbType="NChar(10)")]
		public string MAXE
		{
			get
			{
				return this._MAXE;
			}
			set
			{
				if ((this._MAXE != value))
				{
					if (this._XEMAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAXEChanging(value);
					this.SendPropertyChanging();
					this._MAXE = value;
					this.SendPropertyChanged("MAXE");
					this.OnMAXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="NChar(10)")]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NCC_XEMAY_CHITIETHD", Storage="_CHITIETHDs", ThisKey="MACC_XEMAY", OtherKey="MACC_XEMAY")]
		public EntitySet<CHITIETHD> CHITIETHDs
		{
			get
			{
				return this._CHITIETHDs;
			}
			set
			{
				this._CHITIETHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XEMAY_NCC_XEMAY", Storage="_XEMAY", ThisKey="MAXE", OtherKey="MAXEMAY", IsForeignKey=true)]
		public XEMAY XEMAY
		{
			get
			{
				return this._XEMAY.Entity;
			}
			set
			{
				XEMAY previousValue = this._XEMAY.Entity;
				if (((previousValue != value) 
							|| (this._XEMAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._XEMAY.Entity = null;
						previousValue.NCC_XEMAYs.Remove(this);
					}
					this._XEMAY.Entity = value;
					if ((value != null))
					{
						value.NCC_XEMAYs.Add(this);
						this._MAXE = value.MAXEMAY;
					}
					else
					{
						this._MAXE = default(string);
					}
					this.SendPropertyChanged("XEMAY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_NCC_XEMAY", Storage="_NHACUNGCAP", ThisKey="MANCC", OtherKey="MANCC", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.NCC_XEMAYs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.NCC_XEMAYs.Add(this);
						this._MANCC = value.MANCC;
					}
					else
					{
						this._MANCC = default(string);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHDs(CHITIETHD entity)
		{
			this.SendPropertyChanging();
			entity.NCC_XEMAY = this;
		}
		
		private void detach_CHITIETHDs(CHITIETHD entity)
		{
			this.SendPropertyChanging();
			entity.NCC_XEMAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
	public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANCC;
		
		private string _TENNCC;
		
		private string _DIACHI;
		
		private string _SODIENTHOAI;
		
		private EntitySet<NCC_XEMAY> _NCC_XEMAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    partial void OnTENNCCChanging(string value);
    partial void OnTENNCCChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnSODIENTHOAIChanging(string value);
    partial void OnSODIENTHOAIChanged();
    #endregion
		
		public NHACUNGCAP()
		{
			this._NCC_XEMAYs = new EntitySet<NCC_XEMAY>(new Action<NCC_XEMAY>(this.attach_NCC_XEMAYs), new Action<NCC_XEMAY>(this.detach_NCC_XEMAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNCC", DbType="NVarChar(50)")]
		public string TENNCC
		{
			get
			{
				return this._TENNCC;
			}
			set
			{
				if ((this._TENNCC != value))
				{
					this.OnTENNCCChanging(value);
					this.SendPropertyChanging();
					this._TENNCC = value;
					this.SendPropertyChanged("TENNCC");
					this.OnTENNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODIENTHOAI", DbType="NChar(10)")]
		public string SODIENTHOAI
		{
			get
			{
				return this._SODIENTHOAI;
			}
			set
			{
				if ((this._SODIENTHOAI != value))
				{
					this.OnSODIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._SODIENTHOAI = value;
					this.SendPropertyChanged("SODIENTHOAI");
					this.OnSODIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_NCC_XEMAY", Storage="_NCC_XEMAYs", ThisKey="MANCC", OtherKey="MANCC")]
		public EntitySet<NCC_XEMAY> NCC_XEMAYs
		{
			get
			{
				return this._NCC_XEMAYs;
			}
			set
			{
				this._NCC_XEMAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NCC_XEMAYs(NCC_XEMAY entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_NCC_XEMAYs(NCC_XEMAY entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUONGHIEUXE")]
	public partial class THUONGHIEUXE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHUONGHIEU;
		
		private string _TENTHUONGHIEU;
		
		private EntitySet<XEMAY> _XEMAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHUONGHIEUChanging(string value);
    partial void OnMATHUONGHIEUChanged();
    partial void OnTENTHUONGHIEUChanging(string value);
    partial void OnTENTHUONGHIEUChanged();
    #endregion
		
		public THUONGHIEUXE()
		{
			this._XEMAYs = new EntitySet<XEMAY>(new Action<XEMAY>(this.attach_XEMAYs), new Action<XEMAY>(this.detach_XEMAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUONGHIEU", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUONGHIEU
		{
			get
			{
				return this._MATHUONGHIEU;
			}
			set
			{
				if ((this._MATHUONGHIEU != value))
				{
					this.OnMATHUONGHIEUChanging(value);
					this.SendPropertyChanging();
					this._MATHUONGHIEU = value;
					this.SendPropertyChanged("MATHUONGHIEU");
					this.OnMATHUONGHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUONGHIEU", DbType="NVarChar(50)")]
		public string TENTHUONGHIEU
		{
			get
			{
				return this._TENTHUONGHIEU;
			}
			set
			{
				if ((this._TENTHUONGHIEU != value))
				{
					this.OnTENTHUONGHIEUChanging(value);
					this.SendPropertyChanging();
					this._TENTHUONGHIEU = value;
					this.SendPropertyChanged("TENTHUONGHIEU");
					this.OnTENTHUONGHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONGHIEUXE_XEMAY", Storage="_XEMAYs", ThisKey="MATHUONGHIEU", OtherKey="MATHUONGHIEU")]
		public EntitySet<XEMAY> XEMAYs
		{
			get
			{
				return this._XEMAYs;
			}
			set
			{
				this._XEMAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_XEMAYs(XEMAY entity)
		{
			this.SendPropertyChanging();
			entity.THUONGHIEUXE = this;
		}
		
		private void detach_XEMAYs(XEMAY entity)
		{
			this.SendPropertyChanging();
			entity.THUONGHIEUXE = null;
		}
	}
}
#pragma warning restore 1591
